
version: '2.0'
services:
  web:
    # TODO: build context, ports and redis dependency
    build: 
      context: .
    ports: 
    - "5000:5000"
    links: 
    - redis
    volumes:
      - .:/code
    environment:
      # Makes flask to reload code on change
      FLASK_ENV: development
      FLASK_APP: app
      REDIS_HOST: redis
      REDIS_PORT: 6379
  redis:
    image: redis:6.0-rc4-alpine
    # TODO: missing persistence for redis. You need to persist /data directory.
    volumes: 
    - ./data
